name: ipython-notebook
dependencies:
  - notebook
  - ipywidgets
  - ipython
  - tornado
  - requests
  # get dependencies for pgcontents
  - certifi
  - click
  - mako
  - psycopg2
  - six
  - sqlalchemy
  - nose
  - pip
  - pip:
    - pgcontents==0.5.3
